### ISSUE TITLE
Review performance of custom ValueResolvers

### ISSUE THREAD

**Issue by leekelleher** [leekelleher/umbraco-ditto#105]
Looking at the unit-tests durations on a recent AppVeyor build...

https://ci.appveyor.com/project/leekelleher/umbraco-ditto/build/0.8.0.320/tests

...some of the unit-tests take a while to run.  I had a cursory check of the longer duration tests, and the models that are used in those tests are using some form of custom ValueResolver.

The 2 longer running ones are:

* `AppSettingsTests.AppSetting_Property_Returned()` - uses `AppSettingValueResolver`
* `PublishedContentTests.Complex_Property_Convertered()` - uses an ad-hoc one called `NameValueResovler` (sic)

Currently this is still a gut feeling, but I wanted to flag it on here.

**Comment by JimBobSquarePants** [comment]
That appsettings resolver doesn't sit right with me. The core value resolvers should, in my opinion, be used for resolving values from the Umbraco back office. Pulling a setting can be done easily without Ditto. I think we should be careful not to allow feature creep.

**Comment by leekelleher** [comment]
@JimBobSquarePants I hear you, it's noted. I think we covered most of this in #97? :+1: 

Although with the AppSettings resolver, I thought you approved of it at the time? https://github.com/leekelleher/umbraco-ditto/issues/72#issuecomment-105941454 :trollface:

**Comment by JimBobSquarePants** [comment]
I'm a fickle creature and guilty as any of diamond chasing. :smile:

Does that test improve in performance if the setting is called more than once? .NET caches the values but I'm also wondering whether it lazy loads them?

**Comment by mattbrailsford** [comment]
I've just installed and ran dotTrace and from what I can tell, one of the biggest holdups is ironicly the DisposableTimer, more specifically the call to LogManager.GetLogger taking32% of the processing time (this is within the AppSettings test) Weirdly, on my machine, the ComplexModel test is running in acceptable timings.

**Comment by JimBobSquarePants** [comment]
Interesting... Looking at the [DisposableTimer](https://github.com/umbraco/Umbraco-CMS/blob/a3d4ccc062b94859e446b1206bf21f334577a35c/src/Umbraco.Core/DisposableTimer.cs) code it seems to run all the time regardless of what mode you are in. I wonder whether we should only run it on debug?

[Complex](https://github.com/leekelleher/umbraco-ditto/blob/104dede81677d435d9f415c37bb03d7109e67634/tests/Our.Umbraco.Ditto.Tests/Models/ComplexModel.cs#L23) model contains an AppSettings value resolver so that's probably gonna be causing any delay there also.  I'll run the tests here to see what values I get.

**Comment by leekelleher** [comment]
I had thought that `DisposableTimer` only ran when in debug mode, but I'm probably wrong... I think it's more that MiniProfiler only displays in debug mode.

The `DisposableTimer` stuff are leftovers from the original code (in the Carlsberg projects). Since Ditto's performance has steadily improved, I haven't been monitoring/benchmarking Ditto in MiniProfiler.

I'll branch off and try some tests with removing `DisposableTimer` calls, see if that helps.

---

I'll take a look at `AppSettingValueResolver` too... see what happens with multiple calls, etc.

To be honest, the `PublishedContentTests` set of tests could be separated out to focus on testing specific cases.  It was originally our dumping ground for first tests.

**Comment by JimBobSquarePants** [comment]
The disposable timer code was really useful for diagnosing the issues I was having that lead me to develop the lazy loading proxy factory. If we can keep it, I would.

**Comment by leekelleher** [comment]
@JimBobSquarePants OK, no problemo!

**Comment by JimBobSquarePants** [comment]
Just some numbers on my machine.

- AppSetting_Property_Returned : 337ms
- Complex_Property_Convertered: 78ms

**Comment by leekelleher** [comment]
For `AppSetting_Property_Returned`, I'm getting 46ms, (but I am on a MBP w/ 16GB RAM :neckbeard:)

I've ended up removing the `Complex_Property_Convertered` test in my #106 PR - as it was trying to do too many things.  There are now small (more focused) tests for those (complex-model) features.

**Comment by leekelleher** [comment]
Latest unit-test results from AppVeyor's build of my amends in PR #106:
https://ci.appveyor.com/project/leekelleher/umbraco-ditto/build/0.8.0.326/tests

The noticeable longer ones are...

* `AppSetting_Property_Returned` is 1 sec 514 ms
* `Basic_Id_And_Property_IsMapped` is 807 ms
* `Custom_TypeConverter_Converts` is 197 ms
* `Nested_Enumerable_PublishedContent_Property_Value` is 112 ms

(I'm less worried about the last 2)

**Comment by mattbrailsford** [comment]
So pulled down and running through dottrace again,

AppSetting_Property_Returned 31% is DisposableTimer.DebugDuration, with the next biggest thing being 11% and TypeDescriptor.GetPropertiesImpl

Basic_Id_And_Property_IsMapped 28% is being used by Umbraco.Core.StringExtensions creating a Regex for something, next biggest is 22% and that is DisposableTimer

Custom_TypeConverter_Converts 26% is the regex thing again, and 25% is DisposableTimer

Nested_Enumerable_PublishedContent_Property_Value 23% regex, 18% disposable timer, 13% Expression compilation in EnumerableInvocations.StaticMethodSingleParameter

**Comment by leekelleher** [comment]
I've added in a unit-test for calling `WebConfigurationManager.AppSettings` directly as a benchmark against the custom value-resolver:
https://github.com/leekelleher/umbraco-ditto/blob/develop/tests/Our.Umbraco.Ditto.Tests/AppSettingsTests.cs#L28

The timings from the last AppVeyor build are interesting...

![capture](https://cloud.githubusercontent.com/assets/209066/9168752/e4e1124c-3f50-11e5-8fd7-1ee5f7e5d0f3.PNG)

* `AppSetting_Native_Returned`: 74ms
* `AppSetting_Property_Returned`: 212ms

Interesting that `AppSetting_Property_Returned` times keep varying, feels like there are other moving parts with the build environment. Still it tends to have the longest duration.

**Comment by mattbrailsford** [comment]
Might be worth testing the native test with and without a disposable timer as it's this that I'm finding is the slow bit, not actually accessing the web.config

**Comment by leekelleher** [comment]
Good point @mattbrailsford!  On my machine, `AppSetting_Property_Returned` typically times at ~45ms.  I've commented out all the `DisposableTimer` calls, re-ran the test, it's down to ~30ms.

Furthermore, one subsequent runs, it can go down to 15ms.

---

I'm now wondering what can we do about `DisposableTimer`... the debug info is useful, (as mentioned above).  We could look at extending/overriding it, with a toggle? (Check for `HttpContext.IsDebuggingEnabled`?)

... or is this an Umbraco Core issue? Should `DisposableTimer.DebugDuration` only run in debug mode?

**Comment by mattbrailsford** [comment]
I'd be tempted to submit a PR to add the IsDebugEnabled check to core as isn't this only usefull for the profiler? which itself should only be relevant in debug mode.

**Comment by leekelleher** [comment]
Had a quick look over `DisposableTimer` in Umbraco Core, it has changed somewhat recently (in v7), so I'd need to understand if there are better alternatives now? (There's one called [`ProfilingLogger`](https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/src/Umbraco.Core/Logging/ProfilingLogger.cs) and another, [`LogProfiler`](https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/src/Umbraco.Core/Profiling/LogProfiler.cs) - I'm not sure if those help solve the issue?)

Since we are supporting Umbraco v6.2.5... we're a bit stuck with how `DisposableTimer` was implemented back then.

**Comment by mattbrailsford** [comment]
In that case, wrap it and handle debug ourselves.

**Comment by leekelleher** [comment]
I've started something in #107 :metal:

**Comment by leekelleher** [comment]
Closing this one, as our tests are inconclusive.

Fingers are pointing towards `DisposableTimer` - we can continue that discussion on PR #107 

Otherwise when we find something more concrete, we can reopen this issue or start a new one.
