### ISSUE TITLE
Move "Attributes" folder under "ComponentModel"?

### ISSUE THREAD

**Issue by leekelleher** [leekelleher/umbraco-ditto#110]
Should we move the "Attributes" folder under the "ComponentModel" folder?

It keeps the grouping together with the other component types, (ConversionHandlers, TypeConverters and ValueResolvers)

**Comment by JimBobSquarePants** [comment]
I'd say yes since we're using a flat namespace and it makes sense for this project.

**Comment by leekelleher** [comment]
:+1: Groovy!

**Comment by JimBobSquarePants** [comment]
![groovy](https://cloud.githubusercontent.com/assets/385879/9506630/9d0eb41c-4c8c-11e5-81dd-30fe66091de0.jpg)
