### ISSUE TITLE
Missing method

### ISSUE THREAD

**Issue by djomen** [leekelleher/umbraco-ditto#112]
Hi,

Getting this error on a clean install all setup with nuget - so new mvc app, new umbraco site and then installed ditto and ditto PCM packages using Nuget.

Method not found: 'System.Object Our.Umbraco.Ditto.PublishedContentExtensions.As(Umbraco.Core.Models.IPublishedContent, System.Type, System.Action`1<Our.Umbraco.Ditto.ConvertingTypeEventArgs>, System.Action`1<Our.Umbraco.Ditto.ConvertedTypeEventArgs>, System.Globalization.CultureInfo)'.

I have tried doing an As<Model> in the view but get same issue above as when trying to use PCM published content model)

I have also added the PCM init class.

What am i missing? Or is there an issue?

**Comment by mattbrailsford** [comment]
Can show your code for how you are calling .As?

**Comment by djomen** [comment]
@using Dittotest.Web.Models
@using Our.Umbraco.Ditto
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = null;
    var vm = Model.Content.As<Home>();
}


and with the PCM - 
@inherits Umbraco.Web.Mvc.UmbracoViewPage<Dittotest.Web.Models.Home>

Get the same error with both.

**Comment by djomen** [comment]
Tried adding to another project and got the error so fired up a test instance and getting it again. Been away from Umbraco a while so hope im not missing something stupid! :)

**Comment by djomen** [comment]
Ah i see one issue. I tried PCM first and it didnt work so reverted back to basic usage and forgot to remove PCM from the POCO for Home. Thats fixed the As but still getting the error trying to use the PCM.

The Ditto PCM package is installed.

**Comment by djomen** [comment]
Would still like to get it working with the PCM if you can see the issue.

**Comment by JimBobSquarePants** [comment]
PCM package? You mean the ModelFactory package https://www.nuget.org/packages/Our.Umbraco.Ditto.ModelFactory/

This error sounds to me like the current version of that package has been built against an old version of Ditto. The breaking changes in [0.8.0](https://github.com/leekelleher/umbraco-ditto/releases/tag/0.8.0) will be causing the error. We should ensure that for each Ditto release there is a subsequent ModelFactory release also.

**Comment by leekelleher** [comment]
Oops! I intentionally didn't bump the version number of the ModelFactory package, as we hadn't modified any of the code. #doh! :scream_cat:

I'll sort out the version number, (and also the Ditto dependency - currently it only has a dependency on UmbracoCms.Core)

**Comment by djomen** [comment]
Yes sorry PublishedContentModel. Will give it a whirl to test when all updated. Thanks.

**Comment by djomen** [comment]
Will be looking at the grid and archetype packages too when this done - will those need a rebuild also?

**Comment by leekelleher** [comment]
@djomen Those packages are separate to Ditto, it isn't the same issue as the ModelFactory.

**Comment by djomen** [comment]
Thats cool - just thought id try to be helpful and raise it just in case. :)

**Comment by leekelleher** [comment]
@djomen Are you referring the the Resolvers project? https://github.com/micklaw/Ditto.Resolvers
If so, I'm not too sure... it'll probably need to be recompiled too, (but that's not our project).

**Comment by djomen** [comment]
I pulled the solution down and built and it works so yes - just needs the new build.

**Comment by leekelleher** [comment]
Ditto.ModelFactory v0.1.1 has been released:
https://www.nuget.org/packages/Our.Umbraco.Ditto.ModelFactory/0.1.1
