### ISSUE TITLE
Deprecate legacy Ditto TypeConverters?

### ISSUE THREAD

**Issue by leekelleher** [leekelleher/umbraco-ditto#127]
Following a discussion from the [Our Umbraco forum](https://our.umbraco.org/projects/developer-tools/ditto/ditto-feedback/65149-TypeConverter-not-being-fired#comment-231616)...

> @JimBobSquarePants: I'm actually quite keen to mark all the other converters internal and only expose the `DittoPickerConverter`. That actually uses all the others to do the conversion internally anyway. In my Umbraco solutions I have never used the converters.  `DittoMediaPickerConverter`, `DittoMultipleMediaPickerConverter`, `DittoContentPickerConverter`

:+1: from me on this, as I only use `DittoPickerConverter` myself.

I suggest that we mark the "legacy" TypeConverters with the `Obsolete` attribute, directing developers to use the `DittoPickerConverter` instead.

Open to discussion, etc.

**Comment by sniffdk** [comment]
Sounds like an excellent idea :+1:

**Comment by leekelleher** [comment]
Thanks @sniffdk! :+1: 

Closing this, as PR #128 has been opened.
