### ISSUE TITLE
DittoIgnore on a subclass

### ISSUE THREAD

**Issue by BarryFogarty** [leekelleher/umbraco-ditto#130]
Would be nice if you could apply the [DittoIgnore] attribute on a class - so it was possible to subclass a set of ignored properties on a model.  Quite possibly there is already a way of accomplishing this?

My use case is a member profile model with a set of (ditto ignored) select lists.

**Comment by BarryFogarty** [comment]
Scratch that - figured I can just [DittoIgnore] the property on the main models that point to my subclass!

**Comment by leekelleher** [comment]
Thanks @BarryFogarty.  I'm not sure how much usage there would be for ignoring an entire class. I think most scenarios would be as you've done, adding the ignore attribute to the containing class's property - _nipping it in the bud_, so to speak.

Happy to revisit this if there's a further need for it.
