### ISSUE TITLE
Base Class UmbracoPropertyAttributes ignore Classing Class UmbracoPropertiesAttribute

### ISSUE THREAD

**Issue by jamiepollock** [leekelleher/umbraco-ditto#132]
Hi all,
Lee's asked me to create an issue from [a topic](https://our.umbraco.org/projects/developer-tools/ditto/ditto-feedback/72324-umbracoproperties-prefix-reuse-with-a-similar-base-class) I had started on Our's Ditto forum.

Essentially if I had a base Ditto POCO with a few properties which are standard across except for the UmbracoProperties prefix of the calling class. 

Imagine having a sign up page which has content tabs for Sign Up Form & Sign Up Complete. Using an alt template Action name in the Controller to deviate content.

Base class:
```c#
    public class BasicContentViewModel : IBasicContentViewModel {
        [UmbracoProperty(AltPropertyAlias = "Name")]
        public string Title { get; set; }

        [UmbracoProperty]
        public HtmlString Content { get; set; }        

        [DittoIgnore]
        public bool HasContent { get { return Content != null && string.IsNullOrWhiteSpace(Content.ToString()) == false; } }
    }
```

Implementations using the prefix to change the content.
```c#
    [UmbracoProperties(Prefix = "signUpComplete_")]
    public class SignUpCompleteContentViewModel : BasicContentViewModel {
    }
```
Or...

```c#
    [UmbracoProperties(Prefix = "signUpForm_")]
    public class SignUpFormContentViewModel : BasicContentViewModel {
    }
```

Sadly as the `Title` or `Content` properties live in the `BasicContentViewModel` they don't pick up the `UmbracoPropertiesAttribute`. This is because of [these lines here](https://github.com/leekelleher/umbraco-ditto/blob/develop/src/Our.Umbraco.Ditto/ComponentModel/ValueResolvers/UmbracoPropertyValueResolver.cs#L30:L31).

`this.Context.PropertyDescriptor.ComponentType` resolves to BasicContentViewModel. It's a bit of a head scratcher because the PropertyDescriptor is core .net functionality.

Thanks,
Jamie

**Comment by leekelleher** [comment]
Thanks @jamiepollock.  I've added a unit-test to support this in #133.

I've been looking at ways to get the correct `PropertyDescriptor.ComponentType`, but no joy so far.

**Comment by jamiepollock** [comment]
That's what I concluded too from a generating a quick ValueResolver which returned `this.Context.PropertyDescriptor.ComponentType == null;` in `ResolveValue()`.

In addition doing a Quick Watch on the Context and PropertyDescriptor I didn't see any sign of either `SignUpFormContentViewModel` or `SignUpCompleteContentViewModel` when fishing around wasn't visible at all only `BasicContentViewModel`.

**Comment by leekelleher** [comment]
Closing this one, as I can't see how we're going to fix it.

PR #133 provides a unit-test to show how it fails.  We can continue any discussion over on #133.
