### ISSUE TITLE
Visible Children ValueResolver

### ISSUE THREAD

**Issue by leekelleher** [leekelleher/umbraco-ditto#134]
From reviewing @BarryFogarty's [Merchello Workshop](https://github.com/BarryFogarty/Merchello.UkFest.Workshop) code, there are various part of navigation that call on an extension method `content.VisibleChildren()`.

Essentially it is this code...

```csharp
content.Children.Where(x => x.IsVisible())
```

Current in Ditto if you want to map the child nodes to a model's property, you can use `[UmbracoProperty("Children")]`, which is fine... but it doesn't take into account the "umbracoNaviHide" convention.

What are your thoughts about having a "Visible Children" value-resolver in Ditto core?

```csharp
public class VisibleChildrenResolver : DittoValueResolver
{
    public override object ResolveValue()
    {
        return  Content != null && Content.Children != null
            ? Content.Children.Where(x => x.IsVisible())
            : Enumerable.Empty<IPublishedContent>();
    }
}
```

**Comment by JimBobSquarePants** [comment]
I'm not a fan. You'd need ones for all the other navigation properties and once you start adding all that stuff you might as well start using PublishedContentModel and the factory. 

In my projects I use base classes with the properties I need and use a strong typed wrapper for UmbracoHelper to grab things when I need them.

**Comment by mattbrailsford** [comment]
The only thing I'd be tempted to introduce, though I haven't really thought it through, is maybe some kind of IEnumerable filter attributes, so if you are resolving IEnumerables, we could provide an easy mechanism for filtering the result. I think this differs enough from a value resolver, and it's not a type converter, so could be something we look into?

**Comment by leekelleher** [comment]
I'm unsure about this too, hence starting a discussion (_as opposed to a PR_).

---

@JimBobSquarePants The `IsVisible` extension method is part of Umbraco core, with the "umbracoNaviHide" property alias as a built-in convention. Which is the only reason I'd propose this type of custom ValueResolver.

I have this nagging feeling that we still need to persuade you about the merits of ValueResolvers :heart: (_alas I think we covered it in #97_).

I'd be interesting in seeing more on how you develop sites with Ditto. I'm curious how it all pieces together :+1: 

---

@mattbrailsford I'd thought about filters too, not sure though - feels too much.  If a developer was to write a custom `DittoFilter`, then they might as well write a custom ValueResolver, (or use a conversion handler).

**Comment by mattbrailsford** [comment]
Yea, I must admit, at the start of this whole discussion, I just though "use DittoIgnore and a conversion handler to populate it yourself". Ultimately, conversion handlers are to allow you to do custom logic so I'd say these would probably be the right solution.

**Comment by JimBobSquarePants** [comment]
@leekelleher 

>I have this nagging feeling that we still need to persuade you about the merits of ValueResolvers :heart: (alas I think we covered it in #97).

Truth be told chum I wish we'd used something like the ValueResolvers throughout albeit with the logic that allows you to attach the attributes to both the class and properties as we do the TypeConverters. Having both now causes nothing but confusion plus you get issues with other libraries picking up on the TypeConverters.

Here's a copy of base classes I use in projects to wire things up. There's a few hacks in there but on the whole it works really well for keeping sites under control and extensible.

https://dl.dropboxusercontent.com/u/78716633/DittoExample.zip
