### ISSUE TITLE
CurrentMemberAs attribute

### ISSUE THREAD

**Issue by jamiepollock** [leekelleher/umbraco-ditto#137]
Hi folks,
Just wondering what if using MembershipHelper, a way of turning IMembers into IPublishContent objects, has ever been considered as a core Ditto attribute?

I've been using my own custom value resolver locally with some success. An issue could be a current member isn't always available so how is that resolved? I'll admit I've only used it on controller which are login protected.

Is this feature bloat? I understand Ditto shouldn't cover everything Umbraco does (see the relations PR).

**Comment by mattbrailsford** [comment]
Personally I wouldn't include it in core myself, I think it's probably just
a nice pattern to share. I do similar things with Teacommerce resolving
current store and order. I think these things though are just good for our
own add on libs.

**Comment by leekelleher** [comment]
@jamiepollock, we could always add it to the [labs](https://github.com/leekelleher/umbraco-ditto-labs) repo?

It doesn't necessarily have to be something that we _release_ as such, more as a reference for people's own libraries.

I'll probably move the Relations ValueResolver PR over there too.

**Comment by leekelleher** [comment]
@mattbrailsford Meant to say, could do the same with TeaCommerce, (if re-usable)?
I was thinking similar for Merchello, (since helping Barry with his recent workshop).

**Comment by leekelleher** [comment]
Closing this one.

@jamiepollock I'll set-up a "contrib" VS project over on the [labs repo](https://github.com/leekelleher/umbraco-ditto-labs), if you wanted to collab?
