### ISSUE TITLE
Converting a nested Archetype Model

### ISSUE THREAD

**Issue by ordepdev** [leekelleher/umbraco-ditto#139]
Here is the sample code I'm working on.

    private IEnumerable<ConvertToModel> ConvertFromArchetype(ArchetypeModel value)
    {
        var converter = new AnotherConverter();
        List<ConvertToModel> model = new List<ConvertToModel>();

        value.ForEach(x => model.Add(new ConvertToModel()
        {
            Value = x.GetValue<string>("Title"),
            AnotherValue = (AnotherType)converter.ConvertFrom(x.GetValue("ValueToConvert")))
        }));

        return model;
    }

The problem with nested Archetype Models is when you try to get the value *ValueToConvert* it gives you json style string instead of the actual ArchetypeModel.

The question is: it is possible to do this without creating another class to deserialize the json string?

**Comment by leekelleher** [comment]
Hi @ordepdev,

Within Archetype it internally makes a call to Umbraco's `TryConvertTo<T>` method, so you could try...

```csharp
AnotherValue = x.GetValue<AnotherType>("ValueToConvert")
```

But yes, I believe you'd still need another TypeConverter to convert from an `ArchetypeModel` to whatever `AnotherType` would be.

Hope this helps?

**Comment by ordepdev** [comment]
So, I already have the second `TypeConverter` to convert the type of `ValueToConvert` to `AnotherType` and the property `AnotherValue` is decorated with `[TypeConverter(typeof(AnotherConverter))]`. 

Meanwhile, `AnotherValue = x.GetValue<AnotherType>("ValueToConvert")` does't hit the `AnotherConverter` code and returns null.

**Comment by leekelleher** [comment]
The `TypeConverter` attribute needs to be on the `AnotherType` class itself, (so that .NET's TypeDescriptor can discover it - it doesn't look for the attribute on properties).

**Comment by ordepdev** [comment]
Oh right! Anyway, I was using `GetValue<IEnumerable<AnotherType>>` so... no hit.

Thanks Lee :+1:

**Comment by leekelleher** [comment]
If you want to register a TypeConverter for a generic type, you could add this to your app start-up...

```csharp
TypeDescriptor.AddAttributes(typeof(IEnumerable<AnotherType>), new TypeConverterAttribute(typeof(AnotherTypeConverter)));
```
