### ISSUE TITLE
AppSettings

### ISSUE THREAD

**Issue by djomen** [leekelleher/umbraco-ditto#141]
The AppSettings resolver doesn't seem to be working... unless I've done something wrong.

I have tried with and without passing the name and even tried adding your example.

I have a class:
...

    public class MailSettings
    {
        [AppSetting("MailFrom")]
        public string MailFrom { get; set; }

        [AppSetting()]
        public string MailTo { get; set; }

        [AppSetting("ContactSubject")]
        public string ContactSubject { get; set; }

        [AppSetting("umbracoConfigurationStatus")]
        public string UmbracoVersion { get; set; }
    }

...

and the settings (xml removed):
...
    key="ContactSubject" value="[My Subject]"
    key="MailFrom" value="website@domain.co.uk"
    key="MailTo" value="receiver@domain.com"
...

Upon testing i just seem to be getting null values.

**Comment by leekelleher** [comment]
Hi @djomen - Which version of Ditto and Umbraco are you using? (I'm assuming the latest of both?)

I'll look into it on my local test environment too.

**Comment by djomen** [comment]
Umbraco 7.3.0
Ditto 0.8.3

**Comment by leekelleher** [comment]
Thanks @djomen.  I've tested it out on those versions, (using the same names/values are yours), and it works as expected. The values are populating.

How are you calling Ditto's `.As<T>()` method? I'm curious if something else is at play here.

**Comment by djomen** [comment]
Ah i think i can see what the issue is here - I must obviously be using it incorrectly.

For some reason with this not been content spat out of umbraco and coming from settings I assumedI could just use a basic class (not a page VM).... not sure why i have thought that. Must have been half asleep...

I guess i need to have these properties on the page view model so Ditto can populate.  Or is there a way to call Ditto to map a class with these properties and attributes?

Apologies if i sent you on a wild goose chase.

**Comment by mattbrailsford** [comment]
You can cast any IPublishedContent to any POCO. It shouldnt need to be any
specific type of model.

I'd be interested to see what code didn't work, and what you changed to
make it work.

**Comment by djomen** [comment]
Thats just it - i wasn't pulling an IPublishedContent.  I saw the attribute and thought nice handy little shortcut for a settings class like i've pasted above- instead of just writing the code myself.  Case of me having a lazy moment during a late night i think. Not quite sure how i thought the data was going to get mapped. :)

Ive now written the code i needed like i should have done in the first place. h5is

**Comment by mattbrailsford** [comment]
Ahhh, OK, yea, Ditto is specifically and IPublishedContent to POCO mapper
so you need to start with an IPublishedContent

**Comment by djomen** [comment]
Yep - ill close the non issue! :) Sorry again for the goose chase.
