### ISSUE TITLE
Merge Attributes & Resolvers/Processors

### ISSUE THREAD

**Issue by mattbrailsford** [leekelleher/umbraco-ditto#144]
This kinda relates to my processors issue #142, but I didn't want to muddy that thread with another suggestion so thought I'd raise another issue.

I know I was initially the one to suggest separating a resolver function from it's attribute, but in practice, I'm not sure if this is just creating extra work for the sake of it? Most attributes are 1 to 1 with a resolver/processor, or some just run without an attribute via the DittoValueResolver attribute (or DittoProcessor in my new PR) so I'm wondering if we shouldn't just use attributes and save having to create a separate class. There is also the weird thing right now where an attribute has to reference a resolver/processor type, and that type also has to reference the attribute, creating a circular reference, so it kinda seems naff that you have to create one, then create the other, then update the first one again with the new reference.

My initial suggestion for separating them seemed a good idea, and what would likely be the recommended approach (I don't think attributes should contain logic according to best practice), but given the idea of Ditto is to be simple, I feel like merging these might make things simpler and do away with an extra concept that we don't need.

Wadda you think?

**Comment by leekelleher** [comment]
:+1: I agree.  The circular-ish references never sat right with me, but I didn't have a better suggestion at the time. :stuck_out_tongue_closed_eyes:

It feels like we'll be abusing attribute classes, (with logic) - but I'm all for reducing developer "ceremony".

**Comment by JimBobSquarePants** [comment]
:+1:   I'm all for simplification and I'm not fussed about adding logic to attributes. Microsoft do it with their ActionFilterAttribute in MVC.

**Comment by mattbrailsford** [comment]
This is all being taken care of as part of the processors PR #143
