### ISSUE TITLE
Processors - should they be cancellable?

### ISSUE THREAD

**Issue by leekelleher** [leekelleher/umbraco-ditto#146]
The new Processors feature (#143) essentially creates a pipeline to prepare the value to be set. I'm wondering whether a processor could be cancellable (and effectively exit the pipeline)?

If so, we could make the `DittoIgnore` as a processor. Removing the need for an explicit check.

(Just something to think about - no worries if not)

**Comment by mattbrailsford** [comment]
I can't think of a use case where this would be handy and in fact can just see it yielding unexpected results.

Really, they should just be like type converters, in that they should just check the value + target type to see if they should bother modifying the value. If their checks don't pass, don't change the model, just pass it on to the next processor.

Do you have a use case in mind?

**Comment by leekelleher** [comment]
I couldn't think of another solid use case for it.

Whilst reviewing the code, I was looking at the `DittoIgnore` check and thought "could that be a processor too?"

Then that got me thinking about them being cancellable.

I'll close this off, but wanted to note it down on here - to seed ideas, etc :wink:
