### ISSUE TITLE
OnConverting/OnConverted - reduce code

### ISSUE THREAD

**Issue by leekelleher** [leekelleher/umbraco-ditto#147]
In `PublishedContentExtensions`, both the `OnConverting` and `OnConverted` methods are very similar - preparation code to run the conversion handler.  The differences are the `DittoConversionHandlerType` enum value and custom attribute type.

We could reduce the code for these methods by either adding extra parameters to a consolidated method, or introduce a small abstracted method (e.g. `RunConversionHandlerEvent` or something?)

Again, just a minor suggestion for slimlining the code/class.

**Comment by mattbrailsford** [comment]
I've just pushed some code in commit e6ab421 to make those methods use a more generic method that can handle both. We could drop the OnConverting/OnConverted methods if we wanted to, but I don't mind them just passing off to another method.

**Comment by leekelleher** [comment]
@mattbrailsford Nice one (with e6ab4212d06a2f44e64f30b3f4f55a61e9b4093f), exact how I meant. :smiley: 

I guess we could drop the OnConverting/OnConverted wrapper methods.  Unless, in future, you thought they might contain other logic?

**Comment by mattbrailsford** [comment]
I don't mind them staying. It makes the code higher up not have to know specifics about the OnConvert method. And the importing thing is that we aren't repeating ourselves, repeating ourselves.

**Comment by leekelleher** [comment]
Groovy, we'll leave them in! :shipit:
