### ISSUE TITLE
Swap Out Value Resolution Easily (e.g., for Polyglot)

### ISSUE THREAD

**Issue by Nicholas-Westby** [leekelleher/umbraco-ditto#151]
This is in regards to this thread: https://our.umbraco.org/projects/developer-tools/ditto/ditto-feedback/74048-ditto-with-polyglot

In short, I use [Polyglot](https://our.umbraco.org/projects/backoffice-extensions/polyglot/) to build websites with multiple languages. Here's what that looks like:

![polyglot](https://cloud.githubusercontent.com/assets/5933222/12218433/e68490f6-b6d3-11e5-80c7-4982533f007d.png)

In this case, I have an "About Us" content node of document type "Info Page". Under that is a translations folder. Under that are my translations. My default language is English, and that's stored in properties on the "About Us" node:

![english](https://cloud.githubusercontent.com/assets/5933222/12218444/201d7788-b6d4-11e5-805f-2914cd9adf6b.png)

Spanish is stored in the "About Us (Spanish)" node:

![spanish](https://cloud.githubusercontent.com/assets/5933222/12218449/406c7e30-b6d4-11e5-9360-78f34220d5b8.png)

Due to some URL rewrite magic, the URL for the English page is `/en-us/about-us` and the URL for the Spanish page is `/es-mx/about-us`. However, the translated pages are never routed to (i.e., only the parent node, "About Us" in this case, is routed to).

If I want "Body Text" in the current language (as indicated by the URL), I use this code:

```
var bodyText = Model.Content.LocalizedPropertyValue<string>("bodyText");
```

Notice that I'm using `LocalizedPropertyValue` rather than `GetPropertyValue`. That is an extension method I built that lives here (a custom library for my company): https://github.com/rhythmagency/rhythm.umbraco.extensions/blob/e7df4420dcb75e9216f67ef0cea915a4a867c36f/trunk/Rhythm.Extensions/Rhythm.Extensions/ExtensionMethods/PublishedContentExtensionMethods.cs#L157

What I'd like to do is use Ditto to handle all my mapping like this:

```
var page = Model.Content.As<InfoPage>();
var bodyText = page.BodyText;
```

That won't work though, as Ditto is calling `GetPropertyValue` rather than `LocalizedPropertyValue`. I could create a `ValueResolver`, but then I'd have to decorate each and every property on my model classes with an attribute. It seems like there should be a better way.

Here's one idea:

```
var config = MyHelper.GetInternationalConfig();
var page = Model.Content.As<InfoPage>(config);
var bodyText = page.BodyText;
```

Or maybe I can decorate my classes with some default value resolver:

```
[DittoDefaultValueResolver(typeof(MyInternationalResolver))]
public class TextPage
{
}
```

Or maybe I can set the default value resolver for the application, perhaps in an application started event handler:

```
Ditto.SetDefaultValueResolver<MyInternationalResolver>();
```

To complicate matters further, I'm making heavy use of Archetype, so it would be awesome if whatever solution is implemented works with Ditto Resolvers for Archetype: https://github.com/micklaw/Ditto.Resolvers

And just to mention another consideration, Polyglot has multiple "modes". In the mode I described above, translations are stored in child nodes. However, in another mode, it can store translations in properties with culture-specific suffixes in their aliases (e.g., "bodyText" / "bodyText_es-mx" / "bodyText_fr-fr"). My `LocalizedPropertyValue` extension method accounts for that possibility as well.

**Comment by leekelleher** [comment]
Thanks @Nicholas-Westby! I'll have a chat with @mattbrailsford about the proposed solutions and we'll discuss on here.

**Comment by leekelleher** [comment]
I've developed the proposed idea in PR #152 - we can discuss the implementation on there.

So far there are two entry points... globally and class-level attribute:

```csharp
Ditto.RegisterDefaultProcessorType<MyCustomProcessorAttribute>();
```

```csharp
[DittoDefaultProcessor(typeof(MyCustomProcessorAttribute))]
public class MyCustomModel { ... }
```

**Comment by leekelleher** [comment]
@Nicholas-Westby Any thoughts on PR #152?

**Comment by Nicholas-Westby** [comment]
@leekelleher I believe that would work well for my needs.

I'm assuming a processor would give me access to the current content node being mapped, as my code would sometime need to access child nodes depending on the current culture.

**Comment by leekelleher** [comment]
Yup, no problem accessing the current content node in the new processors - can be done using `this.Context.Content`.

I'll look to merge this into the main "develop" branch this week.

**Comment by leekelleher** [comment]
Closing this issue, the resolution is in PR #152 - any technical discussion can happen over there.
