### ISSUE TITLE
Performance Benchmarking?

### ISSUE THREAD

**Issue by leekelleher** [leekelleher/umbraco-ditto#156]
I heard about the [BenchmarkDotNet](https://github.com/PerfDotNet/BenchmarkDotNet) library today, (via [Scott Hanselman's blog post](http://www.hanselman.com/blog/BenchmarkingNETCode.aspx)).

It would be great to see a range of benchmarks for mapping of hundreds/thousands of `IPublishedContent` objects - in varying complicity.

> An alternative (found from the blog comments) is [NUnitBenchmarker](https://github.com/Orcomp/NUnitBenchmarker)?

Then with AppVeyor we can add the benchmark report as a download on GitHub release pages.

**Comment by JimBobSquarePants** [comment]
Been following the guys who write this for a while now on Twitter waiting for them to announce DNX support. I think we should definitely try to incorporate it into testing.

**Comment by leekelleher** [comment]
Closing, PR #159 introduces Performance Tests (using BenchmarkDotNet).
