### ISSUE TITLE
API reference documentation

### ISSUE THREAD

**Issue by leekelleher** [leekelleher/umbraco-ditto#157]
Since we have such lovely XML comments through our code-base, should we look to auto-generate static API reference? Do we think this would be useful?

For my client work-projects, I've tried Sandcastle ([SHFB](https://github.com/EWSoftware/SHFB)) and [Doxygen](http://www.stack.nl/~dimitri/doxygen/), both produce good results.

Yesterday I was told about [DocFX](https://github.com/dotnet/docfx), which is being used for new .NET Core docs, (and is supported by the .NET Foundation).  I'd be interested in trying it out on Ditto.

We could wire it up with AppVeyor builds - pushing up the latest API ref docs to the GitHub release pages.

**Comment by JimBobSquarePants** [comment]
I made a poor man attempt at using DocFX with ImageProcesorCore but couldn't get it working. (I have an open issue for it https://github.com/JimBobSquarePants/ImageProcessor/issues/297). 

I'm dying to give it a go. The Core docs are sweet! http://dotnet.github.io/api/index.html

**Comment by leekelleher** [comment]
On a side-note, I've been using (and contributing to) [Wyam](http://wyam.io/) recently. It has a [static code analysis module](http://wyam.io/modules/analyzecsharp) that can be used to generate API reference docs.

**Comment by leekelleher** [comment]
Quick update to say that I've started prototyping our docs using Wyam. I haven't pushed my local branch up yet, I'll see how I progress over the next few days.

My biggest concern is the front-end dev, CSS, etc. I'm tempted to do it in vanilla HTML and let you guys work your magic! :wink:

**Comment by mattbrailsford** [comment]
Something like this do?

![capture](https://cloud.githubusercontent.com/assets/527305/15077208/4ad79fe8-13a5-11e6-8ab9-80f2d9aa2ee3.PNG)

**Comment by leekelleher** [comment]
@mattbrailsford Nice!!

**Comment by mattbrailsford** [comment]
Had a look at the docs with a view to coming up with a better structure. What do we think of the following:

- Installation
  - Requirements
  - Our Umbraco Instalation
  - Nuget Instalation
  - Manual Installing
  - Upgrading to 0.9?
- Usage Guide
  - Basic Usage
  - Processors
    - In-built processors
  - Custom Processors
    - Processor Contexts (Advanced?)
  - Chaining Processors
  - Caching Processors
    - Cache Key Builders
  - Conversion Handlers
  - DittoView
  - DittoController (Advanced?)
- Advanced Topics
  - Lazy Loading
  - Factories
- API

Comments?

**Comment by leekelleher** [comment]
Closing this issue off, any discussion can carry on over in PR #170
