### ISSUE TITLE
Question:  ValueResolverContext for Lazy ProperyValueResolvers

### ISSUE THREAD

**Issue by rustyswayne** [leekelleher/umbraco-ditto#158]
Hey guys,

I'm working on a multi site implementation where I pass around a "SiteAlias" in ValueResolveContext.  It all works great until I hit a property that is marked virtual so Lazy (proxy object).  I expected that the instantiated context that I passed into the do the initial model conversion would be used when converting the Lazy properties later, but it appears that a new instance of the ValueResolveContext is being instantiated instead.

Am I missing something in the way I'm using the contexts or is it by design?  

I looked at using an OnConverting method, but it does not expose the context in the handler.

Is there another way to accomplish this?  I've come up with a hack that which I shove stuff into the request cache but it seems pretty wonky. =)

**Comment by JimBobSquarePants** [comment]
Sorry for the slow reply on this. 

I'll try and have a look over the weekend if you can post a code sample of how you are passing the site alias.

**Comment by rustyswayne** [comment]
Sure thing.

In my `BaseSurfaceController` I have

`
        /// <summary>
        /// Gets the resolver contexts.
        /// </summary>
        protected List<DittoValueResolverContext> ResolverContexts { get; }
`

This is inherited by `BaseSurfaceController<T>`

Which includes an 

`
/// <summary>
    /// The base surface controller.
    /// </summary>
    /// <typeparam name="T">
    /// The type of the ViewModel
    /// </typeparam>
    public abstract class BaseSurfaceController<T> : BaseSurfaceController
        where T : BaseViewModel
    {
        /// <summary>
        /// The index.
        /// </summary>
        /// <param name="model">
        /// The model.
        /// </param>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        public override ActionResult Index(RenderModel model)
        {
            var vm = model.Content.As<T>(valueResolverContexts: this.ResolverContexts);
            return this.CurrentTemplate(vm);
        }

        /// <summary>
        /// The index.
        /// </summary>
        /// <param name="model">
        /// The model.
        /// </param>
        /// <param name="siteAlias">
        /// The site alias for the ditto resolver contexts.
        /// </param>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        protected ActionResult RenderForWebsiteContext(RenderModel model, string siteAlias)
        {
            var currentDocumentTypeAlias = model.Content.DocumentTypeAlias;

            //// Allows for and also asserts that all contexts are set to the same site alias
            // ReSharper disable once LoopCanBePartlyConvertedToQuery
            foreach (var ctx in ResolverContexts)
            {
                var resolverContext = ctx as WebsiteValueResolverContext;
                if (resolverContext != null)
                {
                    resolverContext.CurrentDocumentTypeAlias = currentDocumentTypeAlias;
                    resolverContext.SiteAlias = siteAlias;
                }
            }

            var context = new WebsiteValueResolverContext(siteAlias, currentDocumentTypeAlias);
            this.ResolverContexts.Add(context);
            return this.Index(model);
        }
    }
`

The `WebsiteValueResolverContext` does have an empty constructor, the constructor with the arguments is part of my work around ... e.g.

`
  /// <summary>
        /// Initializes a new instance of the <see cref="WebsiteValueResolverContext"/> class.
        /// </summary>
        /// <remarks>
        /// We need to set these up with an event since Ditto requires an empty constructor
        /// </remarks>
        public WebsiteValueResolverContext()
        {
            LoadFromCookie();
        }

/// <summary>
        /// Initializes a new instance of the <see cref="WebsiteValueResolverContext"/> class.
        /// </summary>
        /// <param name="siteAlias">
        /// The site alias.
        /// </param>
        /// <param name="currentDocumentTypeAlias">
        /// The current document type alias.
        /// </param>
        public WebsiteValueResolverContext(string siteAlias, string currentDocumentTypeAlias)
        {
            Mandate.ParameterNotNullOrEmpty(siteAlias, "siteAlias");

            this.SiteAlias = siteAlias;
            this.CurrentDocumentTypeAlias = currentDocumentTypeAlias;
            
            // save values to cookie
            this.Persist();
        }
`

Before I added the `LoadFromCookie` in instances where properties where not marked virtual, context data was present.  It's when the Lazy values are retrieved in the Proxy that the contexts data was null.

**Comment by JimBobSquarePants** [comment]
Hmmm this is interesting. I might have to write a unit test and debug.

According to this line
https://github.com/leekelleher/umbraco-ditto/blob/a6cefa5d2bebb68711588c308d5e5c34e9f60663/src/Our.Umbraco.Ditto/Extensions/PublishedContentExtensions.cs#L345

We are passing the context as normal to the method in the same manner as non lazy properties.

**Comment by JimBobSquarePants** [comment]
@leekelleher @mattbrailsford I'm not sure which one of you wrote the resolver context part but it's got me stumped. 

Reading the code linked above and the line below also it looks to me like we check for an existing context and pass it around if it exists... That _should_ preserve the `ValueResolveContext`. I don't know why it is null.

https://github.com/leekelleher/umbraco-ditto/blob/a6cefa5d2bebb68711588c308d5e5c34e9f60663/src/Our.Umbraco.Ditto/Extensions/PublishedContentExtensions.cs#L443

**Comment by leekelleher** [comment]
@JimBobSquarePants - @mattbrailsford did the resolvers code, but I think we should definitely set up a test to replicate @rustyswayne's scenario. (I'll aim to try it over the next few days - unless someone else gets there first?)

**Comment by rustyswayne** [comment]
@JimBobSquarePants, @mattbrailsford, @leekelleher I'm guessing it's a threading issue where the instantiated resolver contexts are null when the proxy objects start resolving the lazy properties.  If I set default values in the constructors things work - but it's obvious that the resolver(s) are being reconstructed using the defaults so I'm guessing it's a threading issue where the resolver(s) are only available in the thread in which they were instantiated.

**Comment by leekelleher** [comment]
I've made a spike-branch from 0.8.4 tag (from the "master" branch) to try to replicate this scenario.

Updated our existing `ValueResolverContextTests` unit-test on this commit: 1caea769c0601d0c030292bc67182e1b0e3f7d15

Unfortunately I can't reproduce the issue, the custom `ValueResolverContext` is populated when used by a `virtual`/lazy-loaded property.

Unless I'm missing something here?  (Feel free to modify the unit-test in the spike-branch accordingly)

**Comment by rustyswayne** [comment]
Thanks Lee, I'll have a look in the next couple of days.  It may be the way my controller is populating the values ... perhaps I need to use a ConcurrentDictionary rather than a list ...

**Comment by mattbrailsford** [comment]
Just an observation, but looks like you are doing very similar things to Ditflo in that you are hiding the .As calls behind a base controller. a) is there any reason you wouldn't just use ditflo? and b) it would be interesting to know if the issue is present within ditflo too?

**Comment by Nicholas-Westby** [comment]
(*Random lurker interjects*) @mattbrailsford What is Ditflo? I found a repo for it, but no real indication of what it does: https://github.com/mattbrailsford/umbraco-ditflo

**Comment by mattbrailsford** [comment]
It's not officially released (though I have shown it to Rusty I believe, hence my question), but it effectively runs ditto on the fly for your views based upon what model you say your view needs, so negates the need for you to call .As manually. It also does what Rusty is trying to do with the controllers, giving you a means of registering processor contexts and have them automatically passed into ditto, again based upon what you say your view needs.

I really need to write a blog post  on that :)

**Comment by Nicholas-Westby** [comment]
Thanks for the quick rundown. Looking forward to the blog post!

**Comment by rustyswayne** [comment]
@mattbrailsford I think I may actually seen that bit in DitFlo a while ago - but moved it into our base classes.  We considered using it on this project, decided to not to for a number of reasons:

1) A lot of our controllers handle AJAX requests with the fallback to non JS within the same method - so we needed controllers anyway.

2) We are also route route hijacking off of the template names in many cases over and above simply by content type alias.  This may be possible in DitFlo, but to be honest, I did not play with it to that extent.

3) The other developer had never used Ditto before and I don't think I sold DitFlo very well when I gave the introduction.  He is very familiar with MVC and found it more comfortable to do things a bit more hands on.

I have done a Merchello site using DitFlo before and found it quite good.  This one however, is one Umbraco instance that will contain 4 or 5 stores and I agreed with him that having a bit more granular control would likely save us some headaches or at least head scratching =).

I did not think to test DitFlo against the scenario described in this thread.  I'm off this aspect of the until next week trying to get some Merchello core stuff done.  When I get back into it I'll keep you updated.

**Comment by mattbrailsford** [comment]
What is happening on this issue right now? Has any further investigation being done? If so, who is doing this?

**Comment by rustyswayne** [comment]
I'd say close it and I'll post back if I can add anything more.

**Comment by mattbrailsford** [comment]
Cool, feel free to let us know if you find any further information.
