### ISSUE TITLE
Recursive properties break MiniProfiler

### ISSUE THREAD

**Issue by JimBobSquarePants** [leekelleher/umbraco-ditto#160]
Ditto 0.8.4 

It appears that marking a property as recursive using the `UmbracoPropertyAttribute` causes an error as follows 

```
RecursionLimit exceeded.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.ArgumentException: RecursionLimit exceeded.
```

In my website I have a recursive image property for open graph- This is in my base class. As soon as I include that property in the page while trying to use Miniprofiler the error is thrown.

`[UmbracoProperty("OpenGraphImage", "", true)]`

The result is repeatable using both standard and lazy loaded properties. Returning the value recursively using `UmbracoHelper` method does not do the same.

**Comment by leekelleher** [comment]
@JimBobSquarePants I hit this issue on our Carlsberg implementation, as a quick fix, you can add this to your Web.config:

```xml
<system.web.extensions>
  <scripting>
    <webServices>
      <jsonSerialization maxJsonLength="2147483644"/>
    </webServices>
  </scripting>
</system.web.extensions>
```
I set the `maxJsonLength` value at a ridiculous length (e.g. `Int32.MaxValue`), only not to hit it again.

---

We'll keep this issue open, as it will be good to discuss solutions to the actual problem.

**Comment by JimBobSquarePants** [comment]
Ah excellent! Thanks I've been looking for a solution for this for a while.

**Comment by JimBobSquarePants** [comment]
That doesn't solve I'm afraid. MiniProfiler doesn't use those values, rather binding to its own settings. 

https://github.com/MiniProfiler/dotnet/blob/d0c30ec9ace1391af6bed744d5da4cf34e3f7ca4/StackExchange.Profiling/MiniProfiler.cs#L360

I can raise an issue there but there must be a reason we are causing too much recursion. The default recursion level for the JavaScriptSerializer is 100. My tree depth at the moment is 2.

**Comment by leekelleher** [comment]
Hmm, weird - wondering how it worked for me, (I'll revisit my code).

OK, so we're using the `DisposableTimer` calls quite a lot - which we replaced with our own `DittoDisposableTimer`, that disabled logging/profiling when in production mode (debug=false).  I think that's part of v0.8.x releases.

Do we start to look at other ways to reduce the number of `DisposableTimer` calls? or even review where we are using them?

**Comment by leekelleher** [comment]
@JimBobSquarePants ... and would you believe it, reviewing my code, I find this...

```csharp
protected override void ApplicationStarting(UmbracoApplicationBase umbracoApplication, ApplicationContext applicationContext)
{
	// Set the max value of the MiniProfiler JSON response.
	if (umbracoApplication.Context.IsDebuggingEnabled)
		StackExchange.Profiling.MiniProfiler.Settings.MaxJsonResponseSize = int.MaxValue;
}
```

**Comment by JimBobSquarePants** [comment]
Yeah.... I did something similar but It still broke. I'll revisit my solution tomorrow and try again.

One thing I did notice when testing was that Miniprofiler will fail late rather than early. When I have the backoffice open in a different tab. I get readout for that in the frontend tab so it looks like it is working.

**Comment by mattbrailsford** [comment]
Are we ok to close this as "wontfix" as this is ultimately a limitation in MiniProfiler right? (a problem which many other package devs will face)

**Comment by mattbrailsford** [comment]
Have we confirmed that DisposableTimer is the issue?

**Comment by JimBobSquarePants** [comment]
I don't exactly know what the cause is to be honest.

I know that calling a recursive method natively 

`IPublishContent.GetPropertyValue<object>("alias", true);`

Works fine with miniprofiler. 

`[UmbracoProperty("alias", "", true)]`

Will immediately break it.

**Comment by mattbrailsford** [comment]
Are you running from src build? or from official release? Just wondering what would happen if you commented out the usages of DisposableTimer (am guessing turning debug mode off won't allow the profiler to run) or updated it to check a web.config settings as well to disable them?

**Comment by JimBobSquarePants** [comment]
I'm running from a release. I'm gonna experiment with a src build and see how much info we lose if we comment them out.

**Comment by mattbrailsford** [comment]
I've gone ahead and added a check to the Ditto.DebugEnabled property to look for an AppSetting of Ditto:DebugEnabled aswell. If it sees one, it'll use whatever that says, otherwise falls back to the standard .NET debug setting so this should hopefully allow you to disable ditto debugging, whilst keeping the standard .NET debugging so you can use the mini profiler. Just add a setting with key "Ditto:DebugEnabled" and a value of "false" and it should disable them all.

**Comment by JimBobSquarePants** [comment]
That a great idea, I'm gonna go bully the miniprofiler devs now.

**Comment by mattbrailsford** [comment]
Had any luck with this @JimBobSquarePants?

**Comment by JimBobSquarePants** [comment]
Sorry @mattbrailsford  Totally forgot, been helping my wife with a vastly overcomplicated project so working both night and day just now. Will do so asap.

**Comment by mattbrailsford** [comment]
Haha, I'm not forcing you, I just wondered if you'd made any progress :)

**Comment by leekelleher** [comment]
:feelsgood:

**Comment by mattbrailsford** [comment]
Any update @JimBobSquarePants ? :)

**Comment by JimBobSquarePants** [comment]
I think we should just mark it a unfixable. MiniProfiler with Umbraco is so out of date I'd just get laughed out of the issue tracker.
