### ISSUE TITLE
Question: Merge Ditflo with Ditto?

### ISSUE THREAD

**Issue by mattbrailsford** [leekelleher/umbraco-ditto#163]
Given the small size of Ditflo and the potential confusion people not knowing what it is compared to Ditto, I wonder if we should just merge them together and it's all just Ditto? You can of course still use ditto without using the Ditflo stuff (obviously this would be renamed to just be Ditto on merge), it just puts it all in one library so there is no need to explain the difference.

**Comment by leekelleher** [comment]
:100: from me.

I see the `DitFloView` directive as complimentary to the `.As<T>` extension method. It is another entry point for Ditto.

**Comment by mattbrailsford** [comment]
Closing, see PR #164 instead
