### ISSUE TITLE
Review the usage of GetHashCode

### ISSUE THREAD

**Issue by JimBobSquarePants** [leekelleher/umbraco-ditto#165]
Having a quick look through the solution I'm seeing a few uses of code like this.

``` c#
this.GetType().GetFullNameWithAssembly().GetHashCode();
```

By my understanding of how this should work this isn't the correct way to go about it. 

Yes, the `Equals(object)` method will return true when both objects return the same hashcode but two different instances with different contexts or order etc should return different hashcodes. 

So... Is it possible to have the same type appear twice in the a Processor collection, if so we should definitely factor properties into the method? 

Normally if I am overriding `GetHashCode` would implement `IEquatable<T>` and add the equality operators and tie it all together.

What are your thoughts? Am I way off?

**Comment by mattbrailsford** [comment]
Good spot.

In all honesty, I don't even think the Equals/GetHashCode are needed as they aren't used in code for any comparisons. I think this is possibly left over from the ValueResolver implementation, however even then it wasn't really used, so not sure if it was added at the start as a "standard template attribute" and modified.

Given we don't use it, I'd be tempted to say drop it, and if people do anything funky where they require the ability to compare attributes, then we'd look at implementing it?

**Comment by mattbrailsford** [comment]
I've just deleted these methods locally and run all unit tests and they pass (just for any added reassurance)

**Comment by JimBobSquarePants** [comment]
Yeah, I would ditch them if we aren't specifically doing an equality check.

**Comment by mattbrailsford** [comment]
Removed
