### ISSUE TITLE
Setting default values for ValueType objects

### ISSUE THREAD

**Issue by leekelleher** [leekelleher/umbraco-ditto#171]
If a POCO has property that is a ValueType, (e.g. `bool`, `int`, etc), but Ditto can't get a value for it, then we try to set the value as `null`, which throws an exception.

See corresponding unit-test in commit 6f835d8c0a64c4aeba79df50edcfd30d9baf939c.

**Comment by leekelleher** [comment]
@mattbrailsford Just to note, this is in the "release-0.9.0" branch.  No pressure to look into this tonight, I can take a look later (or tomorrow).

**Comment by mattbrailsford** [comment]
Sorted :)

**Comment by leekelleher** [comment]
Awesomeness, thanks Matt!
