### ISSUE TITLE
DittoCache examples

### ISSUE THREAD

**Issue by revolution42** [leekelleher/umbraco-ditto#186]
I have been struggling to get the caching working.

I have tried settings the property on both the class and individual processors and my code keeps getting called.

I have tried copying how it is done from the tests and it does not work.

**Comment by leekelleher** [comment]
@revolution42 Just to check, do you have debug=false (under "system.web/compilation" in your Web.config)? Ditto wont cache if debug mode is enabled.

**Comment by leekelleher** [comment]
Closing this issue, please reopen if you feel it's a bug.
