### ISSUE TITLE
Changes to lazy properties

### ISSUE THREAD

**Issue by mattbrailsford** [leekelleher/umbraco-ditto#190]
In the current version of ditto, a lazy property is defined purely by being virtual. A problem with this is that if you are using a base class with overridable properties, this property needs to be virtual and in so doing, becomes lazy.

Now, there are 2 things I want to discuss here:

1) We keep lazy properties but maybe make them more explicit, maybe by using a new attribute such as

    [DittoLazy]
    public virtual MyPRop { get; set; }

This way, it's clear that you intend this property to be lazy, rather than just assuming all virtual properties are lazy.

2) The more controversial part of the question is, do we need lazy properties at all? 

This feature was introduced early on in ditto's life, when it's place in the world was still being discovered. Now though, we know that we want ditto to be a view models builder, and not just a general mapper. Given that the idea behind a view model is to only make available to the view the properties that are needed by the view, the question is why should lazy properties be needed at all? Because, if we have declared a property on our view model, then it should always be needed and thus there is no need to be lazy.

**Comment by mattbrailsford** [comment]
This to some degree relates to pr #188

**Comment by JimBobSquarePants** [comment]
> 2) The more controversial part of the question is, do we need lazy properties at all?

We need them. I use them constantly and would recommend most people do. Not everyone uses Ditto with view models. I don't and I'd much prefer not to. I have a well established process which works perfectly and allows me to very rapidly create performant websites.

I really don't like the idea of the `[DittoLazy]` attribute at all. The `virtual` keyword is clear enough and is used by every proxy generator out there (Castle, Entity Framework) for interception. Adding an attribute simply adds overhead. 

Devs shouldn't be using virtual properties in ViewModels anyway since Viewodels shouldn't be inheriting from each other. It's pollutant and screams of poor design. If any inheritance is to take place it should be from a single base class which shouldn't require overwriting if designed appropriately.

**Comment by mattbrailsford** [comment]
Hmm, can't help but feel that sounds a little double standards to say we should support lazy when arguably you shouldn't have properties on your view model you don't need, but then to say you shouldn't be using virtual, overridable properties on your view model. Surely we should be either flexible, or opinionated, but to mix the two sounds a little too contradictory. 

An example I had that needed virtual overridable properties was using the polymorphism stuff with nested content. In my example, we created a list of links. We have multiple doc types, one for internal links, one for media and one for external links. In our view model, each view model consists of the same properties Name, Url and Target. To stay DRY then, I created a base Link class with these properties, and extended classes which override the Url property, attributing them with the required processors need for mapping that spacific versions url value. 

This to me sounds like a valid use, but this usage forces the Url property to be lazy. This might not cause any issues, but it could equally cause confusion if a problem does arrive and suddenly you are in IProxy land wondering what is going on.

**Comment by JimBobSquarePants** [comment]
Och I'm not saying that though since I don't use my models a view models. We just use it different methods. 

In retrospect adding the attribute will not cost us much perf wise and allow us to use virtual properties, I'm a go for it.

**Comment by mattbrailsford** [comment]
Non of this is a dig BYW, just trying to have the conversation, and really value your side of the argument. I really like that people use Ditto differently, we just need to make sure when people do, they don't get unexpected behavior, so it's just about how to make it work for everyone.

**Comment by JimBobSquarePants** [comment]
Of course. It's the incredible flexibility of it that I love most. Adding the attributes will only boost that. 😄

**Comment by mattbrailsford** [comment]
Having agreed we will use a DittoLazy attribute, I've started a PR for this, so we can move the discussion over there #191
