### ISSUE TITLE
Documentation using GitHub Pages

### ISSUE THREAD

**Issue by leekelleher** [leekelleher/umbraco-ditto#192]
Now that GitHub Pages can generate from the `/docs` folder, ([see their blog post about it](https://github.com/blog/2233-publish-your-project-documentation-with-github-pages)). We are proposing to switch our docs over to using GitHub Pages/Jekyll.

This would remove our dependency on ReadTheDocs.

We would need to figure out if redirects are possible on RTD.

**Comment by jamiepollock** [comment]
@leekelleher hey Lee, I'd be really keen to get started on this. If we had a direction we'd like to proceed.

Sadly I've not used the latest production of Ditto (v0.10.0) and don't have access to any of my previous projects which I'd usually use. Basically I'm massively out of the loop and would love some form of documentation.

I'd love to contribute to any form of documentation too. It'd be a great experience to relearn things. If that's manually making docs with markdown or annotating class files and using a tool. I'd love to be able to help.

@mattbrailsford @JimBobSquarePants do you guys have any thoughts?

As for RTD, if that still exists could we not just put a banner saying those docs are out of date and check Github Pages.

**Comment by leekelleher** [comment]
Closing issue, PR #222 has been opened.
