### ISSUE TITLE
Base Processor - exposing Umbraco context services

### ISSUE THREAD

**Issue by leekelleher** [leekelleher/umbraco-ditto#200]
From reading Umbraco core's recent [Common Pitfalls & Anti-Patterns](https://our.umbraco.org/documentation/Reference/Common-Pitfalls/) document, should we consider exposing the Umbraco objects via our [`DittoProcessorAttribute`](https://github.com/leekelleher/umbraco-ditto/blob/develop/src/Our.Umbraco.Ditto/ComponentModel/Attributes/DittoProcessorAttribute.cs)? (rather than letting developers use the static singletons)

Of course, under the hood we'd actually be exposing the static singletons, (_since this is how Umbraco core do it - e.g. [`SurfaceControllerFactory.cs`](https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/src/Umbraco.Web/Mvc/SurfaceControllerFactory.cs#L56); not using dependency injection_), this would encourage developers to use our exposed properties, so in future we could potentially replace/inject them (or however Umbraco core team recommend we package devs should do this).

Based on the doc, (and the [Umbraco core's `PluginController` code](https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/src/Umbraco.Web/Mvc/PluginController.cs)), we could expose the following properties...

- `ApplicationContext`
- `UmbracoContext` exposed as `Umbraco`
- `DatabaseContext`
- `ServiceContext` exposed as `Services`
- `MembershipHelper` exposed as `Members`
- `ProfilingLogger` / Logger

> re: `UmbracoHelper` - we shouldn't need to expose this, as it is typically used to retrieve from the content/media cache, whereas we can use `UmbracoContext.ContentCache.GetById` directly.

---

Any thoughts?

**Comment by JimBobSquarePants** [comment]
Yup. Definitely wise.

**Comment by jamiepollock** [comment]
Late to the party, but this would be awesome. :)

**Comment by mattbrailsford** [comment]
Shall we close this and move the discussion to the PR?

**Comment by leekelleher** [comment]
Onwards to #204 

![Let's go!](http://4.bp.blogspot.com/-IFrDWt43SLk/VcaF1FXt3aI/AAAAAAAAlWg/-KGP08YHKRg/s1600/MontyPythonHolyGrail_018Pyxurz.jpg)
