### ISSUE TITLE
XPath Processor?

### ISSUE THREAD

**Issue by leekelleher** [leekelleher/umbraco-ditto#205]
It was discussed a while ago on our Gitter channel that we could have an XPath processor...

re: <https://gitter.im/leekelleher/umbraco-ditto?at=5880a4676c1635643c4bb83e>

... the question is, do we think it would be suitable for the main Ditto project, or something to put into the [lab](https://github.com/leekelleher/umbraco-ditto-labs)?

**Comment by jamiepollock** [comment]
@leekelleher: I could see it working in the core but it's definitely an niche idea.

**Comment by mattbrailsford** [comment]
@leekelleher I think it's useful enough to be a core one. If/when XPath is removed and a suitable replacement added, we can deprecate it then, but until then, it's a nice processor to have.

**Comment by leekelleher** [comment]
OK, I've been using the XPath processor on one of our projects quite extensively... I've gotta say, it's impressive - and (weirdly) fun to dev with! 😃 

I'm starting to prepare a PR for this.  One question... what to name it?

`XPath`, `UmbracoXPath`, `ContentXPath`?

My concern for the naming is that it's not a generic XPath processor; ultimately it's a call to Umbraco's content cache `GetByXPath` method... should the name reflect that?

**Comment by JimBobSquarePants** [comment]
I think the name should probably reflect that or you'll get developers trying to use it for other methods and raising support tickets. Heavy documentation will help there also though.

**Comment by leekelleher** [comment]
I'm currently going with `UmbracoXPath`, but totally open for discussion.

**Comment by leekelleher** [comment]
Closing this ticket, we can continue the discussion on PR #209 😎
