### ISSUE TITLE
Constructor Cache is no longer used

### ISSUE THREAD

**Issue by JimBobSquarePants** [leekelleher/umbraco-ditto#208]
I'm not sure when this change took place but we are no longer using the constructor cache. This produces a performance hit as instead we are always using reflection via `type.GetConstructorParameters()` every time we map the type.

https://github.com/leekelleher/umbraco-ditto/blob/ac17fea47c3d2be3cbca63c10f373cb5312ab2a6/src/Our.Umbraco.Ditto/Extensions/PublishedContentExtensions.cs#L24

Was there a reason for this? Thought I'd check before reimplementing.

**Comment by mattbrailsford** [comment]
Can't think of a reason so probably a regression. Any chance you could add
some kind of unit test around it?

**Comment by JimBobSquarePants** [comment]
Testing would be very difficult as there's no classes doing the work. I can fix the regression though.

**Comment by JimBobSquarePants** [comment]
Turns out it was unused code from a previous optimisation. I've deleted it.
