### ISSUE TITLE
v6 Support

### ISSUE THREAD

**Issue by JimBobSquarePants** [leekelleher/umbraco-ditto#26]
I'm wondering if we could do a Ditto.Compat project for v6? A lot of agencies I know are still using that major version.

I have a load of code written already that will allow v6 support for type conversion and run a custom version of the project that used conditional compilation to spit out the correct code using `#if` 

Obviously there are issues with using the built in generic methods like `Ancestors<T>` since we have no `PublishedContentFactory` but as far as I'm aware that affects v7 also if the factory is not used. Am I correct in that assumption?

I have a base class that contains strong typed equivalents for those methods e.g.  `GetAncestors<T>` just now. I wonder whether we can simply give it the same name... There might be ambiguous reference issues though.

We would have to use `PublishedContentExtended` rather than `PublishedContentModel` for any inheritance but thats not an issue.

What are your thoughts?

**Comment by leekelleher** [comment]
We only compiled against v7.1.4 since that's when the `IPublishedContentModelFactory` was introduced.  To be honest, I'm less convinced that it's a good fit for Ditto - I've considered dropping support for it, (or maybe move to a separate assembly?)

I have no problem with v6 support - it is totally possible. Just that I didn't want the responsibility of testing it (lazy me :anguished:). My current projects are v7.1+, so was easier for me to test against.

re: `Ancestors<T>` - this isn't used in Ditto, is it?

**Comment by JimBobSquarePants** [comment]
I'm happy to test it. I use it all the time. :smile: 

We can keep it in a separate project and include a lot of the files as references from the main project. I'll open a branch of develop to do so. 

Dropping the `IPublishedContentModelFactory` support? I like it. If you use `Ancestors<T>` etc with the factory enabled I'm sure it automatically maps to your type. I'd have to double check some of my code to be sure.

**Comment by leekelleher** [comment]
`IPublishedContentModelFactory` could be moved to a separate assembly? (a la `Ditto.PublishedContentModelFactory` - *gawd that's a mouthful!*)

Ditto doesn't use `Ancestors<T>` verbatim - the model-factory is called whenever the Umbraco core requests an `IPublishedContent` node (internally it checks if a factory is set, then calls `CreateModel()`).

**Comment by leekelleher** [comment]
With v6 support... I'm wondering how far back can we support? (I think `IPublishedContent` was introduced in v4.10.) or is that too far?

**Comment by leekelleher** [comment]
So Ditto could have 2 assemblies:

* `Our.Umbraco.Ditto.dll` - supports v4/v6+
* `Our.Umbraco.Ditto.PublishedContentModelFactory.dll` or `Our.Umbraco.Ditto.v7.dll`

**Comment by JimBobSquarePants** [comment]
Yeah sorry. I didn't mean within Ditto. I meant once you had converted your type. 

I've never really understood the purpose of `Ancestors<T>` etc without a model factory since any casting it does internally isn't going to map property values anyway without it. 

I guess we could start with v6 and then see how far back it works. I wouldn't want to make too much effort trying to make it work in v4. It should just be a couple of tweaks to the converters I've already written for the most part.

I think the following assemblies would be best named.

- `Our.Umbraco.Ditto.dll` 
- `Our.Umbraco.Ditto.ModelFactory.dll`

As we don't really want version numbers in the names plus that is a mouthful!

**Comment by leekelleher** [comment]
> As we don't really want version numbers in the names plus that is a mouthful!

I agree. `Our.Umbraco.Ditto.ModelFactory.dll` is good with me! :100:

**Comment by JimBobSquarePants** [comment]
Win! I'll make a start asap. :metal:

**Comment by leekelleher** [comment]
@JimBobSquarePants Just checking if you've made a start with moving the model-factory to a separate project? If not, I can look at that this afternoon.

(I'll leave the rest of the v6 compat stuff for you :smiling_imp:)

**Comment by JimBobSquarePants** [comment]
Hehehe... Not yet, so fire ahead. Most of it is already written so it should be a doddle.

**Comment by leekelleher** [comment]
Closing issue, resolved in PR #32
