### ISSUE TITLE
Unit Testing?

### ISSUE THREAD

**Issue by leekelleher** [leekelleher/umbraco-ditto#28]
This is a general open question about how could we unit-test Ditto.

Initially I thought about unit-testing the built-in TypeConverters, but I think we'll hit issues with the `UmbracoHelper` context.

Still worth a discussion.

**Comment by JimBobSquarePants** [comment]
How do other people test that stuff? Do we build the Umbraco unit tests solution and reference that?

**Comment by leekelleher** [comment]
I'm not too sure how other projects/packages handle it. I'm assuming, they don't - I've always shied away from it too.

I'll have a dig around over the next few weeks.  It's not something we need urgently.

Cheers, Lee.

**Comment by JimBobSquarePants** [comment]
I can do tests for stuff like the `IsEnumerable` etc anyway. We just need to decide what testing framework to use first.

**Comment by leekelleher** [comment]
:+1: Sounds good as starting point.

I have no preference with testing framework. I tend to only go with MSTest as it comes with Visual Studio. But Umbraco core uses NUnit, (which I have installed/set-up anyway).

**Comment by JimBobSquarePants** [comment]
I'd probably go with NUnit then since it'll probably make our life easier in the long run for compatibility.

**Comment by leekelleher** [comment]
Ace, NUnit it is! :metal:

**Comment by JimBobSquarePants** [comment]
Should be good to merge the `feature/unit-test` branch into dev now that the dependencies are sorted.

We need a lot more tests though.

**Comment by leekelleher** [comment]
@JimBobSquarePants Yup, let's merge it in :+1:
