### ISSUE TITLE
Reflection Caching?

### ISSUE THREAD

**Issue by leekelleher** [leekelleher/umbraco-ditto#3]
Consider caching the reflected objects.

We haven't looked into the performance of the reflection calls (e.g. `GetConstructors` or `GetProperties`), could it be improved?

Maybe a dictionary lookup instance?

    var cache = new Dictionary<Type, PropertyInfo[]>();

**Comment by JimBobSquarePants** [comment]
I have a load of code already written that will cover caching so don't start anything.

**Comment by leekelleher** [comment]
Cool! :sunglasses:

**Comment by leekelleher** [comment]
@JimBobSquarePants Is this covered off in PR #19? Can I close this issue?

**Comment by JimBobSquarePants** [comment]
Yeah I'd say so.
