### ISSUE TITLE
Sort out the documentation

### ISSUE THREAD

**Issue by leekelleher** [leekelleher/umbraco-ditto#30]
Currently the only "documentation" is the [README](https://github.com/leekelleher/umbraco-ditto/blob/master/README.md), which has turned into a massive wall of text!

Look at moving over to using GitHub Pages (on a `gh-pages` branch) in future.

**Comment by JimBobSquarePants** [comment]
I'm getting better at jekyll if you want to use that.

**Comment by leekelleher** [comment]
Yeah, we used Jekyll/GitHub Pages for the [uComponents doco](https://github.com/uComponents/ucomponents.github.com) - it worked out pretty good for us.

I guess it's all the other stuff that comes with it... design, markup, etc.  I dare not mention using a pre-built bootstrap template :goberserk: ;-)

**Comment by JimBobSquarePants** [comment]
I resign! :tongue:

**Comment by leekelleher** [comment]
I've created the `gh-pages` branch and copied over the layout/basis from @JimBobSquarePants's ImageProcessor doco site.

http://leekelleher.github.io/umbraco-ditto/

Next up to write actual documentation! :-)

**Comment by JimBobSquarePants** [comment]
:+1: Good man! Looks great! 

Definitely stick to markdown as much as possible. I regret not using it from the start with the IP docs. It's been painful switching over.

**Comment by leekelleher** [comment]
I've been taking a look at Read the Docs this evening... it looks quite promising!

Project page: https://readthedocs.org/projects/umbraco-ditto/
Docs: http://umbraco-ditto.readthedocs.org/en/develop/

I'm testing it out with the [MkDocs](http://www.mkdocs.org/) engine.

**Comment by JimBobSquarePants** [comment]
Anything that makes writing docs easier gets my vote :+1:

**Comment by leekelleher** [comment]
Let's go with Read the Docs! It lets us focus more on the documentation than presentation/styling - which is what I ended up spending a load of time on with the GitHub Pages one.

With RTD, I like that we can have docs per version and it's all within the one repo (with branches/tags).

I'll take a look to see if I need to give you guys any permissions on the RTD side of it... but I think it's a case of update the markdown files in the /docs folder and commit/push to GitHub - then there's a webhook that triggers RTD.

If you want to see if the docs build was successful, I think that page is openly accessible:
https://readthedocs.org/builds/umbraco-ditto/

**Comment by leekelleher** [comment]
re: RTD permissions - if you do need access, then sign up on RTD, then give me your username. I can add you as a Maintainer. ta-dah :tada:

**Comment by leekelleher** [comment]
Going to close this issue, as we'll give RTD a go - it looks like the best place to host docs.

Next up is to write the docs.  We can open separate issues for specific documentation topics.
