### ISSUE TITLE
Support for Relations?

### ISSUE THREAD

**Issue by leekelleher** [leekelleher/umbraco-ditto#36]
@Hendy [mentioned this in the Gitter chatroom](https://gitter.im/leekelleher/umbraco-ditto?at=54f6ec0bdf52f34314e52685).

Consider adding support for Relations.

    [RelationType("relationTypeAlias")]
    public object RelatedItems { get; set; }

Then Ditto could get the related node IDs for the associated `IPublishedContent` node and pass the value to the POCO property.

e.g. `@Model.RelatedItems` could return a `IEnumerable<IRelation>` object type?

Details of the [`IRelation` interface can be found here](https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/src/Umbraco.Core/Models/IRelation.cs).

Then for more complex types a custom TypeConverter can be used:

    [RelationType("relationTypeAlias")]
    [TypeConverter(typeof(RelationsTypeConverter))]
    public IEnumerable<IPublishedContent> RelatedItems { get; set; }

Then the custom `RelationsTypeConverter` can work out how to convert an `IEnumerable<IRelation>` into `IEnumerable<IPublishedContent>`.

**Comment by leekelleher** [comment]
One concern might be that the `IRelationService` call hits the database? Do we know if Umbraco caches the result in memory?

**Comment by mattbrailsford** [comment]
I'd say make sure to use the Lazy<T> class so that they are only loaded when someone tries to access them. Don't want to slow down general Ditto for an edge case.

**Comment by leekelleher** [comment]
:+1: on `Lazy<T>`.

At this stage, I'm only noting this as an idea.  If we think it is too much of an edge case, then we can shelve it.

**Comment by JimBobSquarePants** [comment]
I've just pushed a new branch for you to look at. `feature/allow-relations`

This contains a change to the `PublishedContentContext` class.

The context `PropertyDescriptor` property now points to the property on the target class that is currently being converted. This allows us to parse any attributes on that property from within a custom `TypeConverter` Using the `PropertyDescriptor.Attributes` property.

I *think* that would be enough to allow what is needed. Am I correct?

**Comment by leekelleher** [comment]
You're correct!

Actually thinking about it, this might remove the need for having my [`UmbracoDictionaryValue` attribute](https://github.com/leekelleher/umbraco-ditto/pull/22), as it could be handled the same way - within a specialised/custom TypeConverter.

**Comment by Hendy** [comment]
@JimBobSquarePants perfect :)

@leekelleher how about a caching factory, that'll supply 'clean' POCOs (ones that don't inherit from PublishedContetModel) so once slow relations are inflated, they are in the object graph cache

**Comment by leekelleher** [comment]
@Hendy - we already have pre/post event hooks during the conversion - see [`EventHandlers.cs` source](https://github.com/leekelleher/umbraco-ditto/blob/develop/src/Our.Umbraco.Ditto/EventArgs/EventHandlers.cs). You could roll your own? (Unless I'm missing a bigger benefit?)

**Comment by JimBobSquarePants** [comment]
Awesomesauce! 
@leekelleher  Shifting that into it's own `TypeConverter` would  clean up the `GetTypedProperty` method a little anyway. It seems a good fit also and we only get strings from that don't we?

**Comment by leekelleher** [comment]
Cool. I'll look to remove the `UmbracoDictionaryValue` attribute (and associated code). I'll branch it off so that I can rework it later.

**Comment by JimBobSquarePants** [comment]
Ok coke... Should be simple enough too do. We still on for a release tomorrow?

**Comment by leekelleher** [comment]
Yeah, should be good for tomorrow!
