### ISSUE TITLE
Execute TypeConverter if value is null

### ISSUE THREAD

**Issue by Hendy** [leekelleher/umbraco-ditto#48]
Hi, if a value is null, it seems that TypeConverters aren't called, running a TypeConverter on a null value could be useful to set a default fall-back value (for when something hasn't  been selected in the cms)

**Comment by JimBobSquarePants** [comment]
Makes sense to me. We do null type checks within the converters anyway. 

@leekelleher @mattbrailsford  Thoughts?

**Comment by Hendy** [comment]
(PR: #49)
