### ISSUE TITLE
Multiple TypeConveters ?

### ISSUE THREAD

**Issue by Hendy** [leekelleher/umbraco-ditto#50]
Hi, wondering if it would be possible to have multiple type converter attributes applied to a property, and have them executed in order ?

For example, may be useful to have a more generic type converter first: saved value to `IEnumerable<IPublishedContent>` and then a more specific type converter to be executed after converting the `IEnumerable<IPublishedContent>` to `IEnumerable<ProjectSpecificPOCO>`

    [RelationsTypeConverter("exampleRelationTypeAlias")] // (supplies param to RelationsTypeConverter)
    [TypeConverter(typeof(RelationsTypeConverter)]    
    [TypeConverter(typeof(ProjectSpecificTypeConverter))]
    public IEnumerable<MyPoco> MyPocos { get; set; }

**Comment by mattbrailsford** [comment]
Wouldn't you just have your upper typeconverter inherit from the base one?

Will have to check what type converters are meant to do as standard,
whether that is supported, but I would think inheritance and a single
attribute would be the way.

**Comment by Hendy** [comment]
@mattbrailsford yup, that makes sense, although multiple TCs would mean that the 2nd TC doesn't need to know anything about the 1st, so potentially less combinations of specific all-in-one-TCs might be required. 

I wonder if forcing the use of only the first TC would result in more verbose, but cleaner code ?

**Comment by JimBobSquarePants** [comment]
I'm afraid you can't add multiple TypeConverter attributes to a class or property. It won't compile.

**Comment by Hendy** [comment]
arh ha, well that resolves that idea :)

**Comment by leekelleher** [comment]
@Hendy An alternative would be to look at using `ConvertedType` event hook (or Func delegate)?

Then you can add in any project-specific logic in there.
