### ISSUE TITLE
Prefix Core TypeConverters with "Ditto"

### ISSUE THREAD

**Issue by JimBobSquarePants** [leekelleher/umbraco-ditto#56]
We already do that for the `DittoPublishedContentModelFactory` and it would prevent ambiguity and stop me having to do things like.

    using EnumConverter = Our.Umbraco.Ditto.EnumConverter;

**Comment by leekelleher** [comment]
(Soz for the delay in my replies - been caught up with the other DocType packages :sunglasses:)

Good point! Prefixing with Ditto is a great idea.

It's like with the `HtmlStringConverter`, it isn't a straight `string` to `HtmlString` converter, it relies on certain Umbraco logic, so yep, we should name accordingly.

**Comment by JimBobSquarePants** [comment]
Ace. Will do!

**Comment by leekelleher** [comment]
Closing, fixed in c62165de575e81d4e5757f3e6924278dc56ba4f1
