### ISSUE TITLE
Error when using a TypeConverter that returns a string (Model property is a string)

### ISSUE THREAD

**Issue by Hendy** [leekelleher/umbraco-ditto#61]
When a model returns a single string property, and a custom TypeConverter also returns a single string, an error occurs within Ditto at:

https://github.com/leekelleher/umbraco-ditto/blob/develop/src/Our.Umbraco.Ditto/Extensions/PublishedContentExtensions.cs#L466 

with:
Object of type 'System.String' cannot be converted to type 'System.Collections.Generic.IEnumerable`1[System.String]'.

**Comment by leekelleher** [comment]
Closing issue, fixed by @JimBobSquarePants In 816fc871c9365cb7965c2c6e5d76addb5918abfb - due for release in next version.
