### ISSUE TITLE
Ditto Branding

### ISSUE THREAD

**Issue by leekelleher** [leekelleher/umbraco-ditto#71]
I've been thinking about Ditto's branding... the Pokemon thing started as a joke, which we've far out grown now :wink: 

@mattbrailsford Do you have any ideas for a logo similar to your DTGE/NC logos - black circle with nice logo (not sure if you used the [Noun Project](https://thenounproject.com/) previously?)

@JimBobSquarePants I've been playing with some CSS for the Ditto name - take a look...

https://jsfiddle.net/leekelleher/uqtc2k3k/

... do you know wide support is for `text-shadow`?

Totally open for suggestions, etc :sunglasses:

**Comment by leekelleher** [comment]
From the Noun Project...

**Duplicate** ... This could be adapted to use a "D" instead of squares? or is that too cheesy? 
https://thenounproject.com/term/duplicate/17674/

**Transform** ... I like this one. Could be used as is (with CC-attrib)
https://thenounproject.com/term/transform/20381/

**Comment by JimBobSquarePants** [comment]
Aww man... I'll miss his wee smiley face!

You're right though, we should probably make it look a bit more professional. I'd still like a splash of colour in whatever we produce though.

In answer to your question, text-shadow has pretty good support. IE10+ and all the others.
http://caniuse.com/#search=text-shadow

Btw If you use the first icon with D's you pretty much have Daredevil's logo.

https://duckduckgo.com/?q=daredevil+symbol&iax=1&ia=images

**Comment by mattbrailsford** [comment]
Hmmm, maybe something with the ditto mark?
http://en.m.wikipedia.org/wiki/Ditto_mark

I'll take a look in a bit.

Matt

**Comment by mattbrailsford** [comment]
Either of these?

[image: Inline images 1] [image: Inline images 2]

**Comment by leekelleher** [comment]
> *I tried to edit your comment @mattbrailsford, but I think markdown is disabled in comments via email.*

Here they are...
![ditto2](https://cloud.githubusercontent.com/assets/527305/7831647/9e5020ba-0450-11e5-820f-6ca7fd8f26ed.jpg)
![ditto1](https://cloud.githubusercontent.com/assets/527305/7831648/9e531e5a-0450-11e5-8f91-4ae20f2f5ad4.jpg)

**Comment by mattbrailsford** [comment]
Yea, I figured the same.

**Comment by JimBobSquarePants** [comment]
Throwing an idea I had in the mix. Represents an element in the period table since they are building blocks for everything. The colour is the colour of the original Pokémon.

![ditto-bluprint](https://cloud.githubusercontent.com/assets/385879/7832263/9b30bd68-0455-11e5-9617-5008b6d18cb4.png)

**Comment by mattbrailsford** [comment]
hey @JimBobSquarePants, personally I think it's a bit wishy washy in colour, and as a concept a bit Adobe like. Sorry.

**Comment by leekelleher** [comment]
I really like the "//" one :-)

re: colours - been thinking about the pokemon purple, but red feels stronger

**Comment by JimBobSquarePants** [comment]
That's why I don't design stuff :stuck_out_tongue_closed_eyes:

**Comment by leekelleher** [comment]
Me either... @mattbrailsford got a degree in graphic design, (if I recall correctly?), so I leave it with him ;-)

**Comment by mattbrailsford** [comment]
Shhh, don't got telling everyone, or they'll all want me to design stuff. Programming is much more cut and dry :)

**Comment by kgiszewski** [comment]
===^ Cat is out of the bag now ;)

**Comment by sniffdk** [comment]
Haha, indeed it is :D

**Comment by leekelleher** [comment]
Closing issue, we've gone with the "//" logo!
