### ISSUE TITLE
web.config AppSetting resolver ?

### ISSUE THREAD

**Issue by Hendy** [leekelleher/umbraco-ditto#72]
How about a resolver to get a value from appSettings (in web.config) ?

**Comment by leekelleher** [comment]
Good suggestion! It's totally possible... more of a question of do we want this in Ditto core, or side project? (e.g. [micklaw's Ditto.Resolvers](https://github.com/micklaw/Ditto.Resolvers))

**Comment by Hendy** [comment]
well, no 3rd party references would required (and it'd be tiny)

**Comment by Hendy** [comment]
it could, if the value was null, then use the property name as the key, or if a value had been set, then use that value for the key

**Comment by mattbrailsford** [comment]
I'm not completely averse to this one. I think as long as it's pure Umbraco or pure .NET, then it could be core. Things like the Archetype one are 3rd party dependent, so a no no.

**Comment by leekelleher** [comment]
:+1: Cool with me.  @Hendy do you feel up for a PR? :smile_cat:

**Comment by JimBobSquarePants** [comment]
Nice!

**Comment by Hendy** [comment]
Any prefix for AppSettingAttribute / AppSettingValueResolver ?

**Comment by leekelleher** [comment]
Sounds good to me! :+1:

**Comment by leekelleher** [comment]
Implemented in #73
