### ISSUE TITLE
Re-applying IPublishedContent to a POCO property

### ISSUE THREAD

**Issue by leekelleher** [leekelleher/umbraco-ditto#78]
(Feature sparked from discussion in #77)

--

Let's explore the idea of having Ditto re-apply the `IPublishedContent` from a POCO on one of it's own properties.

An example with code would be...

```csharp
public class MyModel
{
    [DittoReapplyContent]
    public MyOtherModel MyProperty { get; set; }
}
```

Obviously `DittoReapplyContent` is an absolutely terrible name... *suggestion welcome!*

This would be the equivalent of doing: `foo.MyProperty = content.As<MyOtherModel>()`.

**Comment by mattbrailsford** [comment]
[SubValueResolver]?

**Comment by jamiepollock** [comment]
Keeping with convention of [UmbracoProperty], [DictionaryProperty], Could we go with [ContentProperty] or [NodeProperty]?

This could lead the notion of value resolvers for IPublishedContent like it's self to or Children to List/IEnumerable<T>

**Comment by leekelleher** [comment]
![I CAN BE ANYTHING](https://s-media-cache-ak0.pinimg.com/236x/2c/68/50/2c685099120f5548a26fa6acc0ef5239.jpg)

**Comment by JimBobSquarePants** [comment]
I think we're going down a rabbit hole sparked by a misunderstanding of the chronology of object creation. Normally if you are assigning a property value during initialisation then you would be assigning fields or properties with private setters. In that case Ditto would ignore them. 

Ditto already has DittoIgnore which is designed specifically for situations where we want to go outside the norm. 

We most certainly shouldn't be reapplying values as that is expensive and could lead to issues with virtualisation.

Bang a type converter attribute on the other class or property if you want to resolve it. They work perfectly.

**Comment by leekelleher** [comment]
@JimBobSquarePants Not sure if your reply was meant for here for #77?
In a nutshell, the idea would be to have a ValueResolver (attribute) use the same `IPublishedContent` on a (POCO) property. (Would that be expensive?)

I'll prototype something out... we can discuss naming it later :8ball:

**Comment by mattbrailsford** [comment]
I think it should be perfectly valid that someone may want to map the same IPublishedContent to multiple POCO's as that to me is one of Ditto's biggest advantages, allowing you to work with more fine grained models, rather than one big page level model. 

My only quandry really is just whether we do support it via a simple attribute, or require people to manually wire this in a callback (which is what we currently have to do).

**Comment by JimBobSquarePants** [comment]
Yeah soz guys, #77 for that. On my mobile, in the back of beyond...

**Comment by mattbrailsford** [comment]
@JimBobSquarePants shouldn't you be on your hunnymoon? :)

**Comment by leekelleher** [comment]
@JimBobSquarePants Go enjoy & relax mate! We're just spitballing ideas :metal:

**Comment by leekelleher** [comment]
Closing issue, opened PR #79
