### ISSUE TITLE
Invalid constructor parameters exception message

### ISSUE THREAD

**Issue by leekelleher** [leekelleher/umbraco-ditto#80]
Review the exception message for when an object/type has invalid constructor parameters.

https://github.com/leekelleher/umbraco-ditto/commit/40a41d235d7c722dfe3d0a95d7cdd0b435944cf5#diff-81cfd4fcb771a0cad63163155354443cR290

**Comment by leekelleher** [comment]
Do we need to add more to the exception message to explain why the construction parameters are invalid?

**Comment by mattbrailsford** [comment]
Fixed in commit dcf04d89805c902abde8a090a45ee28404d02c3b by adding a more helpful message
