### ISSUE TITLE
Nullable DateTime

### ISSUE THREAD

**Issue by Hendy** [leekelleher/umbraco-ditto#81]
if a POCO has a nullable DateTime? property and the value to convert is empty or not set, the POCO property value is set to DateTime.MinValue.

**Comment by JimBobSquarePants** [comment]
Hmmm... That'll be coming straight from Umbraco.

**Comment by leekelleher** [comment]
I think Umbraco's `TyrConvertTo` is setting the `default()` value, which for `DateTime` would be `DateTime.MinValue`.

**Comment by Hendy** [comment]
@JimBobSquarePants @leekelleher arh, thanks, I'll do some more digging (I had made an assumption it was DItto) and raise an issue where appropriate.

**Comment by leekelleher** [comment]
It's a good question, I've just tried `default(DateTime?)` in LINQPad and it returns `null`, so yeah looks like an issue for Umbraco core.

**Comment by jamiepollock** [comment]
@Hendy I think [this](https://github.com/umbraco/Umbraco-CMS/blob/ded1def8e2e7ea1a4fd0f849cc7a3f1f97cd8242/src/Umbraco.Core/PropertyEditors/ValueConverters/DatePickerValueConverter.cs#L41) is what you were looking for?

**Comment by JimBobSquarePants** [comment]
I have a great [method](https://github.com/JimBobSquarePants/ImageProcessor/blob/c957771d2076a988b3334aafce152ab86e6dafac/src/ImageProcessor.Web/Helpers/QuerystringParser/QueryParamParser.cs#L214) I use in ImageProcessor for returning default values. Returns null for `DateTime?`

**Comment by Hendy** [comment]
@jamiepollock yup, looks like it :+1: I wonder what the consequences of updating that PVC to return null would be ?
