### ISSUE TITLE
Fix up the MkDocs menu syntax

### ISSUE THREAD

**Issue by leekelleher** [leekelleher/umbraco-ditto#82]
Following up on comments from here:

https://github.com/leekelleher/umbraco-ditto/commit/c764b2ad4c5e24b7996576a88c3a2beb88dabc4d#commitcomment-11501134

**Comment by JimBobSquarePants** [comment]
We really need to push on with the documentation before adding any more features. I'm struggling to keep track.

**Comment by mattbrailsford** [comment]
Are the docs working and just need filling in? Or are there still issues?

**Comment by leekelleher** [comment]
Docs are working... they need populating.

ReadTheDocs project page is here: https://readthedocs.org/projects/umbraco-ditto/

The docs are automatically built from the /docs folder.

If you need admin access to the ReadTheDocs, then sign-up on the site and give me your username.

**Comment by JimBobSquarePants** [comment]
Ok coke. I'll have a dig and add what I can.
