### ISSUE TITLE
Rename "EventHandlers" class to "DittoEventHandlers"

### ISSUE THREAD

**Issue by mattbrailsford** [leekelleher/umbraco-ditto#84]
It looks more explicit in code when using ditto event handlers

**Comment by leekelleher** [comment]
I'm fine with this (breaking) change.

**Comment by mattbrailsford** [comment]
Fixed in commit b287f4bab8e4261ed78214fb38368026725d7bb8

**Comment by JimBobSquarePants** [comment]
Agreed.
