### ISSUE TITLE
"Map" versus "Convert"?

### ISSUE THREAD

**Issue by mattbrailsford** [leekelleher/umbraco-ditto#88]
In the context of the converting / converted events, does use of the word "convert" make sense, or should we use something more like "map"? or are these so similar it doesn't make much difference?

**Comment by leekelleher** [comment]
Good question! I'll chew on it too.

I think we used "Convert" due to that we were using TypeConverters.

I guess with "Map", we're not strictly mapping... We're creating, mapping
and converting values/types.

Still good point to be discussed more.

**Comment by JimBobSquarePants** [comment]
I originally thought stick with "Convert" but the more I think about it I would rename them to "Map". Conversion is simply sometimes the means by which we map the properties.

**Comment by leekelleher** [comment]
Closing this issue, any discussion can continue on PR #96
