### ISSUE TITLE
Test ImageCropper mapping

### ISSUE THREAD

**Issue by leekelleher** [leekelleher/umbraco-ditto#89]
A question was raised on the forum about how Ditto maps with the ImageCropper data:

https://our.umbraco.org/projects/developer-tools/ditto/ditto-feedback/66353-imagecropper-mapping-with-ditto

Currently I have no idea, but wanted to flag it up here so we can try it out.

**Comment by jamiepollock** [comment]
Afraid I can't add to this, I usually use a nuPicker or MNTP to filter out a CroppedImage media type, this means an author can reuse a single cropped image anywhere on a site without worrying, my code will handle the correct crop. It does mean the data type has a lot of crop types though.

So typically my conversion will come from a IPublishedContent which calls GetCropUrl().

In my case in v0.7 I guess I'd use a custom resolver which gets out a string from a picked media node and have the crop alias and property alias (just in case) to find it. This is a different direction than @Jeavon was going on the forum which I think is purer to the solution required here.

**Comment by Jeavon** [comment]
I'm going to create a v3 prerelease of my value converters shortly which will have a converter to ImageCropData and a GetCropUrl extension method for ImageCropData also

**Comment by jamiepollock** [comment]
Good to know, @Jeavon. Thanks!

**Comment by leekelleher** [comment]
Closing this issue. The replies on the forum provide a sufficient solution.

https://our.umbraco.org/projects/developer-tools/ditto/ditto-feedback/66353-imagecropper-mapping-with-ditto#comment-221601

// Thanks @jamiepollock and @Jeavon for your feedback!
