### ISSUE TITLE
Option to invert boolean umbraco properties

### ISSUE THREAD

**Issue by mattbrailsford** [leekelleher/umbraco-ditto#92]
Wonder if we should add an "invert" attribute on the UmbracoPropertyAttribute to allow you to invert a boolean. For example, say you have a "Hide" checkbox on a doctype, but in your viewmodel you want the property to be IsVisible, we could just flag this to invert and have the resolver handle the switch?

The only issue being it only really applies to booleans, so is pretty useless for every other property value type.

**Comment by jamiepollock** [comment]
Sounds like a sensible option, but surely you'd change the POCO property to be IsHidden rather than IsVisible?

**Comment by mattbrailsford** [comment]
The issue really pops up when you have multiple checkbox options and you've named them because of how the checkbox works so you end up with HideX, ShowX depending on what the default action should be. The only reason for this suggestions is so that on your viewmodel at least, you can reference them all in the same way.

**Comment by jamiepollock** [comment]
Sure, I see! I'd probably go for InvertedBooleanValueResolver though, personally find it more descriptive than a BooleanValueResolver with a flag inverting things.

**Comment by mattbrailsford** [comment]
Hmm, I wonder if this should actually be an InvertBooleanTypeConverter rather than a value resolver as at this point you know it's resovled as boolean, and it's a case of converting it (ie, inverting it)

Note to self, the lines between Value Resolvers and Type Converters can get a little blury :)

**Comment by jamiepollock** [comment]
Yea, I'm still not up to speed yet as I've not used 0.7.0 in anger. My mind is still in the TypeConverter frame of mind.

**Comment by mattbrailsford** [comment]
Wadda you know, this works :) 

![capture](https://cloud.githubusercontent.com/assets/527305/8209521/3b647a3a-1505-11e5-9d7c-56b2f82e43d6.PNG)

**Comment by jamiepollock** [comment]
badda bing, badda boom! (instant regret for typing that, leaving it there anyways)

**Comment by mattbrailsford** [comment]
Sweet! Well I'm happy with this as a solution so gonna class it as closed. Thanks for you input @jamiepollock (I'll ignore your last comment ;))

**Comment by leekelleher** [comment]
I know you've closed this, but it got me thinking about the difference between ValueResolvers and TypeConverters... my take on it here would be that you are manipulating the value, so that would come under a resolver.  Whereas if you were changing the type, that would be a converter.

I dunno... apples and oranges :bowtie:

**Comment by mattbrailsford** [comment]
I think this is where the lines blur. To me, you've resolved a value already, which is the boolean, then you want to convert  it into another type, which in this case is an inverted boolean.

Like I say, you could do either, I just think this is less messy, ie, you don't have an attribute config setting that only applies if the value is boolean.

**Comment by leekelleher** [comment]
:+1: :100:

**Comment by JimBobSquarePants** [comment]
I'm kinda glad this is closed as it feels a little icky to me. Inversion like this should be blatantly obvious in the code. I like to be able to trace a models properties easily from the back office to my view.
