### ISSUE TITLE
Error rendring a macro

### ISSUE THREAD

**Issue by dunston** [leekelleher/umbraco-ditto#93]
I'm trying to render a macro in a richtext editor, and it fails in the frontend.

If i disable Ditto i renders fine.

Umbraco: 7.2.4
Ditto: newest from source.

YSOD
![image](https://cloud.githubusercontent.com/assets/794203/8228544/f0ec5d1e-15af-11e5-82bc-a1fc49875ea1.png)

**Comment by mattbrailsford** [comment]
Are you trying to resolve the RTE value through Ditto? or are you saying
Ditto is stopping you from rendering any RTE value with a macro in
altogether? ie, just trying to render it via @Umbraco.Field()

**Comment by leekelleher** [comment]
Hi @dunston, I see from the stack-trace that you're using the ModelFactory.  Other people have ran into issues with using it too.  Personally I stopped using it as I hit some issues - that I couldn't fix.

We'll take a look, but to set expectations - don't hold your breath :scream_cat:

**Comment by JimBobSquarePants** [comment]
Quite a few of the issues associated with eager loading in the manner we do (which conflicts with ModelFactory) can be solved by marking the property as `virtual` which invokes lazy loading.

Could you give that a try?

**Comment by leekelleher** [comment]
@dunston Any updates? Did marking the property with `virtual` work for you?

**Comment by dunston** [comment]
@leekelleher sorry the delay.

Making it ´virtual´ did the trick thx.

**Comment by JimBobSquarePants** [comment]
Excellent! Another win for the ProxyFactory! :fireworks:

**Comment by leekelleher** [comment]
Cool, thanks for the update @dunston.

**Comment by naepalm** [comment]
Just ran into the same problem and marking the property virtual worked. Thanks guys!

**Comment by JimBobSquarePants** [comment]
Great to hear!
