### ISSUE TITLE
Register a custom Conversion Handler 

### ISSUE THREAD

**Issue by leekelleher** [leekelleher/umbraco-ditto#98]
Since the global `DittoEventHandlers` have been removed, would we be able to a custom `DittoConversionHandler` for a model-type, (at app-startup), so that we can manipulate the object post-conversion.

A proposed example would be:

    DittoConversionHandler.RegisterHandler<MyModel, MyModelConversionHandler>();

**Comment by mattbrailsford** [comment]
Created pull request #99 which will solve this so lets continue the discussion there.
